Dao #3 Task
IvanLuchkin/java-dao pull request #1
Opened 2021-01-11 16:35 UTC by IvanLuchkin

Task completed.

2021-01-11 16:58 UTC, Vedroid approved these changes

2021-01-11 16:58 UTC, Vedroid commented on src/main/java/manufacturing/service/ManufacturerServiceImpl.java
> +        return manufacturer.get();
```suggestion
        return manufacturerDao.getById(id).orElseThrow(() ->
                        new RuntimeException("Manufacturer with id " + id + " not found"));
```

2021-01-11 17:34 UTC, IvanLuchkin commented on src/main/java/manufacturing/service/ManufacturerServiceImpl.java
> +        return manufacturer.get();
Done, thanks!

2021-01-12 07:27 UTC, Sofasmile requested changes
good job)

2021-01-12 07:27 UTC, Sofasmile commented on pom.xml
do we need junit dependency in the pom.xml file? let's remove it

2021-01-12 07:27 UTC, Sofasmile commented on src/main/java/manufacturing/service/ManufacturerServiceImpl.java
> +    ManufacturerDao manufacturerDao;
```suggestion
    private ManufacturerDao manufacturerDao;
```

2021-01-12 07:27 UTC, Sofasmile commented on src/main/java/manufacturing/dao/ManufacturerDaoImpl.java
> +        Storage.getManufacturers().put(id, manufacturer);
we can move this logic to the Storage class. Example:
```
Storage.saveManufacturer(manufacturer);
```

2021-01-12 07:27 UTC, Sofasmile commented on src/main/java/manufacturing/dao/ManufacturerDaoImpl.java
> +        manufacturerToChange.setCountry(newManufacturer.getCountry());
better replace newManufacturer in the map:
```
Storage.getManufacturers().put(newManufacturer.getId(), newManufacturer);
```
this code is more flexible. We shouldn't change the logic of this method if the manufacturer object is changed

2021-01-12 07:27 UTC, Sofasmile commented on src/main/java/manufacturing/dao/ManufacturerDaoImpl.java
> +            throw new RuntimeException("Manufacturer " + id + " not found");
```suggestion
            return false;
```

2021-01-12 10:45 UTC, Sofasmile approved these changes

2021-01-12 10:45 UTC, Sofasmile commented on src/main/java/manufacturing/dao/ManufacturerDaoImpl.java
> +        if (!manufacturers.containsKey(id)) {
```suggestion
        if (!Storage.getManufacturers().containsKey(id)) {
```

2021-01-12 10:46 UTC, merged